[package]
name = "loomark"
version = "0.0.1"
description = "Loomark local-first Markdown desktop editor"
authors = ["Loomark contributors"]
edition = "2021"

[lib]
name = "loomark_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
notify = "8.2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
